---
title: "Synopsis Paper II"
author: "Bas Machielsen"
date: "8/23/2021"
fontsize: 8pt
output: 
  beamer_presentation:
    includes:
      in_header: preamble.tex
classoption: "aspectratio=169"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Chapter 1: Introduction

## Transformation of European Politics

One of the most important and influential developments in modern history has been the rise and gradual expansion of democratic governments in Western Europe. Over the course of the nineteenth century, many European countries adopted a parliamentary system, the rule of law, and implemented a separation of powers and accountable government. Additionally, arguably the most significant reforms have been the rise of suffrage and eligibility expansions, making the political arena accessible for virtually every citizen, and fiscal reforms encompassing taxation to help secure a small amount of unemployment insurance and pensions. By contrast, in the early 19th century, many (Western) European countries were virtually indistinguishable from autocracies, and were dominated by a small oligarchical elite around the autocrat, usually the king or emperor. 

Yet, most of these countries embarked on a series of reforms that started with the establishment of parliamentary sovereignty and increasing its power vis-a-vis the autocrat, and that culminated about a century later with universal suffrage. Simultaneously, and in face of changing economic circumstances, these states have also seen a transition from a minimalist government, occupying itself primarily with defense spending, to a government actively intervening in the lives of its citizens, for example, by securing unemployment benefits and pensions, and by actively levying taxation. Observers tend to identify two major breaking points in this transformation, the first being when the autocrat relinquishes absolute power in favor of constitutional rule, and the second being the establishment of universal suffrage. 

Historically, in the period that marked the transition from parliamentary oligarchy to parliamentary democracy, governments and parliaments were dominated by a narrow political elite for a long time. In virtually all Western European countries these elites simultaneously chose to gradually extend the franchise, but at the same time limited government spending and welfare spending, so that government size and intervention remained far from reaching the proportions of present-day (post-WWII). Illustrative examples of this trajectory include Sweden, Germany, the United Kingdom and the Netherlands (Lindert, 2003). 

## What do we already know?

This transition from autocracy to democracy has been widely studied in various disciplines. In particular, political scientists and economists have offered both theoretical and empirical explanations for why incumbent politicians in an oligarchic political system in which they stood to benefit would agree to potentially far-reaching reforms. Theoretically, various authors have pointed to factors as electoral expediency (Lizzeri and Persico, 2004; Aidt, Franck, and Dutta, 2010), the threat of revolution and mobilization (Acemoglu and Robinson, 2000), or strategic behavior and bargaining between various factors of the elite (Llavadar and Oxoby, 2005). Przeworski (2009), summarizing the literature up until then, largely agrees that suffrage was conquered rather than granted.

The aforementioned largely theoretical work spawned many empirical studies incorporating some micro-level research (Ziblatt, 2008; Aidt and Jensen, 2014; Aidt and Franck, 2015), focusing on specific key episodes of democratization in particular countries and institutional settings (in case: analyzing several reforms in the United Kingdom) as well as macro-level research encompassing multiple countries (Dincecco, Federico and Vindigni, 2011; Aidt and Jensen, 2017), both of which have found evidence that threats of revolution and public activity played a significant role in extending the franchise. Other research has demonstrated that politicians embrace suffrage reform (e.g., Przeworski, 2008; Ziblatt, 2008) or introduce other important changes in the rules governing national elections (Capoccia, 2010b) when it is in their electoral or strategic interest in the short term. 

## What do we already know? 

Secondly, there has been an active literature explaining government size and taxation. Lindert (2003) contains a detailed study about spending patterns and democratization in European and North American states, and shows several findings hinting at a positive correlation between the two. On the macro-level, Dincecco (2011) conducts an empirical study about political transformations and public finances. Similarly, Aidt et al. (2010) and Chapman (2018) find that franchise extension is not associated with increased public spending. Corvalan et al. (2015) find that the extension of suffrage does not increase or decrease government size, when eligibility requirements are in place. They do find that removal of eligibility requirements, leads to the election of less wealthy politicians and the enactment of more redistributive policies in a sample of US states. 

## Why Does Self-Interest Matter?

The above discussion illustrates that, when looking at the politicians who decided upon the reforms, the theoretical and empirical consensus in economics and political science is that their behavior is characterized by the pursuit of self-interest. The literature has identified various mechanisms, such as the threat of revolution, electoral expedience (public opinion), and competition (threat of losing the elections), that motivate politicians. One question that these theories do not address is the puzzle why it generally took over a century for politicians to implement universal suffrage (Przeworski, 2009), and why similar reforms concerning fiscal legislation or government intervention did not materialize. The present study investigates to what extent politicians' self-interest playing a role in their decision-making. 

There are many reasons to suppose that politicians care about their *financial* self-interest, which has been left out of the focus up until now, both theoretically and empirically. According to Clark (2012), European political elites were dominated by the same groups until several decades after the installment of parliamentary regimes. Other authors (REF, REF and REF) also document the persistence of political elites, which even after parliamentary reforms remained dominated by a small class of individuals. Furthermore, Piketty (2014), Machielsen (xxxx) and other anecdotal evidence (Magraw, 1986 for France) also confirms that politicians were often extremely wealthy, belonging to the upper quantiles of the wealth distribution in their countries, and remained so for a significant time. In many countries, the nobility was overrepresented in parliamentary circles (REF). Hence, the literature contains a paradox that has not been resolved so far: why did politicians in an oligarchical system approve these far-reaching electoral reforms, and why did they not follow suit with fiscal legislation or government intervention, and what was the role of politicians' self-interest in this transformation?

## Approach

To answer these question, I turn to the case of the Netherlands. The Netherlands is an emblematic case from the perspective of European transition to democracy: the Netherlands became a constitutional monarchy in 1848, and took until 1918 to implement universal suffrage after the First World War. In comparison to other countries.. [Explain why it is a good case among all European countries.] During the transition period, the political system also shares many characteristics with other countries: it is a bicameral system, where lower house elections take place in a district system, and the parliamentary arena was initially populated by insiders, and gradually diversified. 

This study focuses on the influence of politicians' self-interest on this transformation. But what is exactly the self-interest of politicians? In this paper, I employ arguably the most obvious proxy for a politician's self-interest: their personal wealth. Using newly-collected probate inventories collected from various archival sources, I retrieve a reliable picture of politicians' personal wealth. I then analyze the influence of politicians' personal wealth, amid many other factors suggested by competing theories, on their voting behavior in a host of important fiscal reforms, suffrage extensions and government interventions. In particular, using extensive data on asset class returns, I attempt to control for wealth differences due to portfolio allocation 

Personal wealth might causally influence voting behavior because acceptance or rejection of reforms might influence politicians' future cash flows in various ways. To ensure a causal interpretation of the estimates, we employ several estimation procedures. In particular, we provide instrumental variable (IV) estimates of personal wealth on the propensity to vote for reforms, instrumenting parental wealth by an indicator whether the politician's father was also politically active. I also rely on various other alternatives to limit the bias caused by endogeneity by relying on (plausibly exogenous) timing of death among politicians. 

# Chapter 2: Key Laws in the Transition

## Political Transition and Oligarchical System - Suffrage

To a large extent, the far-reaching changes across Europe in the nineteenth century can be characterized by three ensembles of reforms: franchise extensions, government intervention and fiscal legislation. An increase in active suffrage encompasses the relaxation (or abolition) of the requirements that granted individuals the right to vote. The key laws underlying these changes were implemented in a series of constitutional changes, which legitimized and implemented these expansions, and happened in the Netherlands in 1887, 1896, 1917 and 1918. It is also noteworthy that the trajectory did not happen without recoil: several law projects attempting to extend the franchise (in 1872 and 1896) were also rejected on various grounds. 

In the Netherlands, the franchise extension likely had many effects, the most obvious being that the diversification and broadening of the electorate also caused a shift in parliamentary composition: whereas parliaments were historically dominated by the nobility and circles close the autocrat, over time, parliaments become more diverse, but still dominated by a layer of legal specialists, theologians and other trained men. The degree of consensus underlying these franchise extensions also varied from project to project, allowing for sufficient variation in voting behavior to be studied. 

## Political Transition and Oligarchical System - Suffrage [2]

Suffrage extensions might impact the state of the world, about which might care, in various ways: suffrage extensions might again increase equality and equity, or the opposite, depending on the ideological viewpoint. Suffrage extensions might also represent a shock to expectations about future governments, parliaments and corresponding future laws and future states of the world, which politicians might anticipate and factor in their decisions. 

Franchise extensions can also influence a politician's wealth: directly, franchise extensions might increase competition, and hence decrease the likelihood of them being able to stay in politics, which might reduce their rents and employment prospects. Indirectly, it might represent a shock to expectations about future governments and parliaments, which might influence future fiscal policy. Politicians might anticipate this when deciding whether to vote in favor of a suffrage extension. 

## Political Transition and Oligarchical System - Gov't Intervention

Secondly, as documented by Lindert (1994), the general view of the state as a passive actor guaranteeing only the security of its citizens evolved into views that accorded the state a more interventionist role, although opinions about exactly how far that should go differed sharply. The responsibility for such a shift in attitudes across the continent lies with increasing social tension and poverty that came with industrialization. This initially prompted many parliaments to approve and oversee legislation prohibited child labor and establishing legal working hours. This served as a precedent for a more interventionist role of the state in markets and economic life of its citizens more generally: in the case of the Netherlands, the era of 1870 to 1920 is marked by several laws regulating education (1900), housing (1901), higher education (1904), labor contracts (1907), among others. Significantly, and in contrast to several other countries, the majority of these laws burdened not the state, but private actors such as employers with the execution (and financing) of these provisions, rather than the state. In the decade starting from 1910, some exceptions to the rule are laws attempting to instigate a state pension (1913, 1916), which were only executed later.

## Political Transition and Oligarchical System - Gov't Intervention

Politicians might care about the state of the world through their particular ideology. Government intervention can influence the state of affairs in the world in a multitude of ways. Government intervention encompasses intervening in markets that were otherwise untouched. They represent many of the special cases touches upon above. For example, the compulsory education laws in 1901 likely increased equality and equity, the 1874 law regulating child labor helped children and the poor more generally, and the law regulating strikes (1903) might have solved one problem (strikes) but caused another (more revolutionary potential) according to at least some politicians. Similarly, the 1901 housing law might have disproportionately concerned particular groups (workers), and laws regulating labor contracts (1907) and offering protection to workers might or might not have had the intended effects (securing the position of workers vs. creating unemployment), depending on the politician's ideology. 

There are also direct and indirect ways in which accepted legislation can directly influence a politician's wealth: government intervention not concerning the government budget may influence politicians' wealth indirectly in ways dependent on the specific law: laws regulating labor (e.g. labor accident law 1901; labor contract law, 1907; sick leave law, 1913) might influence the wealth of politicians who own firms or shares, who might have a lower profit rate. Similarly, the 1901 housing law might have lead to increased municipality-level taxes, and might have lead to decreased equilibrium rent payments (the effect of which is positive/negative depending on the real estate holdings of the politician) because of increased housing supply. More indirectly, The anti-striking laws of 1904 might have reduced the amount of strikes, decrease the loss of firms, and increase the wealth of shareholders. The compulsory education law (1900) might have increased wages and decreased profits due to increased scarcity of labor. 

## Political Transition and Oligarchical System - Fiscal Reforms [1]

Thirdly, despite that most government intervention targeted to limit governmental transfers, government size steadily increased, reaching levels significantly higher than ever before in history, although not nearing the standards of present-day. Increased government spending was necessitated by several exogenous trends: the stalling of revenue from colonies necessitated higher domestic taxation to balance the budget, but the aforementioned expansion of the government into many areas of life also required funds. The tax system, based predominantly on excise duties and tariffs was also widely considered to be outdated. Finally, and most significantly, social tensions and perceived inequity were widespread, and arguably shifted the consensus towards acceptability of increasing taxation, sometimes even rendering taxation progressive.

The most important developments in fiscal legislation include the creating and development of an income tax (1893 and 1914), which included a progressive tax rates. The 1914 hike in turn increased basic tariffs and progressivity. The other major source of tax revenue was inheritance taxation, which established a basic tax rate on inheritance to lineal descendants in 1878. The rates were increased in 1911, 1916, and 1921, but unlike the income tax, there was no progressivity. 

Fiscal legislation can influence the state of the world, to which politicians might accord utility, in several ways: apart from personal financial gain, which the next paragraph will address, fiscal laws might bring more equity and equality into the world, which politicians might value or disvalue. Fiscal legislation also increases government size. Furthermore, taxation can involve a societal dead-weight loss, which might lead some politicians to weigh this against the potential societal benefits. 

## Political Transition and Oligarchical System - Fiscal Reforms [2]

- Out of all law categories, the impact of fiscal legislation on politician's wealth is most obvious: in case of an increase in taxation, the expected costs $C_i$ for a politician as a function of their income (income tax Inc) or wealth (inheritance tax Inh) can be approximated: 

$$
C^{\text{Inc}}_i = \sum_{t = 0}^{T}\frac{\tau_i \cdot Y_{it}}{(1+r)^t}  \text{ and } C^{\text{Inh}}_i = \frac{\gamma \cdot W_i}{(1+r)^T}
$$

where $\tau_i$ and $\gamma$ are the income-dependent (progressive) tariff and inheritance tariff for politician $i$, $Y_{it}$ and $W_{i}$ are a politician's income and wealth respectively, $T$ is the expected lifespan from the time of acceptance of the law, and $r$ is an exogenous interest rate. Concretely, using the law transcripts of $\text{Inc}$ and $\text{Inh}$ laws, an estimate of both costs, using $r = 0.03$ (the avg. interest rate) and $T=20$ (the average lifespan of a politician after voted).. 

- [Do this calculation with a few numbers and stress that wealthier politicians pay more]

- [Stress that wealthier politicians are less inclined to vote "no" when maximizing their utility]
Accepting that $Y_{it}$ and $W_{i}$ are correlated, it is easy to see that politicians who are wealthier experience higher expected costs from acceptance of the law. 

- [Stress that acceptance of taxation also creates public goods, which benefits politicians, but unlikely the wealthy politicians, so that effect is aggravated]

- [Stress that this calculation could happen in other laws, but less obvious, as stressed in previous examples]

# Chapter 3: Measuring Wealth and Voting Behavior

## Methodology: Controlling for Wealth Composition 

## Methodology: Estimating the Effect of Wealth on Voting Behavior

In the political economy literature (as in Trebbi, Sufi, Mian, 2010), politicians' preferences are usually modeled as a function of their ideal policy and some component that reflects self-interest. In this context, the acceptance of each of these laws can influence politicians' utility in two ways: it can influence the state of the world in such a way as to come either closer to their ideal state, $p^*_i \in [0,1]$, or farther. Secondly, political are supposed to care about their financial interests. Both considerations might lead them to decide upon accepting the laws according to: 

$$
U(p, C_i) =  -(p_i - p_i^*)^2 + \beta \cdot f(p, C_i) + \epsilon_i^p
$$

where $p \in \{0, 1 \}$ is the acceptance of the law, and $f(p, C_i)$ is a function representing the impact of the acceptance of the law on their own wealth by taking into account potential _personal_ cost to the politician $C_i$. A politician's $p^*_i$ may also be thought of as *ideology*, the way in which politicians value the state of affairs in the world. 

## Methodology: Estimating the Effect of Wealth on Voting Behavior - Ideology

Laws can impact the state of affairs in the world in various ways. First, politicians might have preferences over social and societal outcomes that might be affected by the law. For example, politicians might be convinced that the particular government intervention increases equality and equity, helps poorer individuals in general, or helps a particular ethnic, religious or economic group (all of which they may or may not value). They might also think the opposite, meaning the law can potentially disadvantage certain groups, such as employers, employees, a certain demographic, etc., all of which they might again value or disvalue according to their worldview. 

Keeping their moral values and preferences over social outcomes fixed, politicians might also not be convinced that the law in question solves the problem it attempts to solve, or indeed creates additional problems outweighing the initial problem. For this reason, their preferred outcome for such a law would be $p^*_i = 0$. Furthermore, some politicians might be ideologically in favor of free markets, and any government intervention can be thought of as bringing disutility to this group of politicians, which would be reflected in $p^*_i = 1$. It is also known that some socialists thought that government intervention did not go far enough, or that some conservatives thought that it went too far. This can be reflected in a $p^*_i \in (0, 1)$, meaning that they suffer utility loss from a law that is less than somebody who is absolutely against it if accepted or absolutely in favor of it when rejected. Finally, politicians' might also feel animosity or hostility towards a particular colleague, leading them to prefer the law to be rejected, despite any eventual merits the law might have. 

## Methodology: Estimating the Effect of Wealth on Voting Behavior - Wealth

To keep the structure as simple as possible, I assume that:

$$
f(p,C_i) = \begin{cases}
C_i &\mbox{ if } p_i = 1 \\
0 &\mbox{ if } p_i = 0
\end{cases}
$$
Meaning that politicians would factor the cost of a law in their decision, as if the acceptance would depend only on their vote. Combining this observation with the fact that $\frac{\partial C_i}{\partial W_i} > 0$, I deduce that the higher a politician's wealth, the lower the probability they vote in favor of a law. Alternatively, if politicians' self-interest would not influence their decision, there would be no relationship between a politician's personal wealth and the probability of voting in favor of a law. 

- Why not structural, and what to do instead?

## Sources

- [Table of dissent vote]

- [Descriptive Statistics Table]

# Chapter 4: Analysis

## OLS Analysis

## IV Analysis

## Harnas Analysis

# Chapter 5: Robustness Checks

## Alternative Estimates OLS

## Alternative Estimates IV

# Chapter 6: Interpretation and Conclusion

## Interpretation

## Conclusion

<!--
## Impact on Personal Wealth

What more should be in this section?

- How can these laws influence the (long-term or short-term) position of politicians?

  - Explain how politicians can care about ideology and their own finances (and that of their children)
  
  - Then, explain how each of these laws influences worldview (ideology) and some of them also influence finances?
  
  - Within finance, make a distinction between direct effects (fiscal laws) and indirect effects. 
  
  - Graph/table detailing the effect of the laws and calculations how, as well as theoretical/historical illustrations
  
## Theory

Systemic:

- Electoral System
    - Term limits
    - Electoral Expedience (= Gain more votes)
    - Competition
- Media (Information) 
    - (Enikolopov, Makarin, Petrova, 2020)
    - (Acemoglu, Hassan, and Tahoun, 2017)
- Threat of Revolution/Unrest
- Disclosure

Personal: 

- Ideology
- Wealth
- Interest groups / Networks / Clan
- Privilege 

- This paper: analyzes to which extent and in which contexts these models are appropriate. 

- Politicians were afraid of fictionalization but not of democratization - nothing to fear, but they were concerned about their own position (and that of their descendants)


Four important questions in the introduction:

- Main research question: What motivates politicians?
    - Self-interest vs. Ideology

- Subquestion: What determines government size?
    - Levels of taxation
    - Public spending
    - Government intervention

- Subquestion: Why did countries transition from oligarchy to democracy?
    - Pol. econ. literature identifies various factors (socialism, )
    - Dutch historical literature: compromise

## Introduction

- Motivation of politicians:
    - Constraints versus ideology: _People have different self-interests, and these are still the dominant force governing how people vote. (Lindert, 2003)_

- Government size: 
    - Analysis of tax hikes and government intervention sheds light on politicians' decisions
    - Only in tax hikes self-interest plays a role
    - Ideology plays a major role

- Suffrage extensions
    - Literature quantitatively investigating particular episodes of democratization at the microeconomic level (such as Capoccia and Ziblatt, 2010; Berlinski and Dewan, 2011; Aidt and Franck, 2019)
    
I answer these questions by means of the setting Netherlands 1870-1920. 

## Why the Netherlands?



## Implications

What lessons can be learned from the results?

- Ideology major driver of voting decisions

- Direct proxy of self-interest applies only in certain cases

- Influence on government size, economic development

- View of agency problems in politics to be revised:

Then the ideological-part of the utility function is more important. 

- Several commonly-thought mechanisms to be discounted (little to no influence)

## Implications


My findings are consistent with Cappocia and Ziblatt (2010), who hold that "rather than class being the single variable that explains how and why democracy came about, scholars can see how religious conflict, ethnic cleavages, and the diffusion of ideas played a much greater role in Europe’s democratization than has typically been appreciated." 

Furthermore, my findings pose a question to the theories that hold that the threat of revolution, or (peaceful) agitation, or even the electorate's preferences are responsible for incentivizing politicians to approve of suffrage reforms. In particular, it seems that ideology and expedience are the most important factors driving the democratization vote, coupled with the likely fact that politicians had nothing to lose in terms of personal wealth. Hence, the certain factors mentioned by theorists and other empiricists alike were not necessary for disciplining politicians into supporting suffrage reforms. The role of these factors is further made unclear by me showing that the system did allow them to pursue personal interests when they came into play - and that this was not prevented by several monitoring mechanisms.


## What motivates politicians?

Two perspectives in the literature: 

- Historico-political: ideology, personal strife and chemistry

    - Case of the Netherlands: consensus within, dissensus between
    
- Political economy: politicians are opportunistic agents who need to be constrained in their behavior




## What motivates politicians?: Literature

## What determines government size? 

- Two dimensions of government size: 

    - (i): taxation and public spending
    - (ii): government intervention in markets
    
- Case of the Netherlands shows that these are not necessarily correlated: Netherlands 1870-1920 taxation and public spending remains very limited, whereas government intervention increases. 

- Intervention in markets: from a minimalist state to a more interventionist state 
    - Precursor of the welfare state

## What determines government size?: Literature

- Lindert: _Why so big? That is, why did social spending expand to claim over one- third of national product in so many countries?_

- _Why was this rise so much greater in some countries than in others?_

## Why did countries transition?

- Political economy literature focuses on self-interested politicians

    - Benefits: electoral position, averting revolution
    
    - Dutch historical literature: ideological compromise 
    
- My findings: suffrage expansion not costly for politicians (limited fiscal changes)

## Why did countries transition?: Literature

## Conclusion: Implications

- Lindert: _Will today’s developing countries and transition economies go through the same history?_

--> 


